"""Core ontology data models: nodes, edges, relationships, and graph events."""

from dataclasses import dataclass, field
from datetime import date
from enum import Enum
from typing import Optional


class NodeType(str, Enum):
    COMPANY = "Company"
    TECHNOLOGY = "Technology"
    SECTOR = "Sector"
    CONCEPT = "Concept"
    PRODUCT = "Product"
    PERSON = "Person"
    REGULATION = "Regulation"
    LOCATION = "Location"
    THEME = "Theme"
    EVENT = "Event"                 # Business events: factory expansion, shortage, etc.


class RelationType(str, Enum):
    DEVELOPS = "DEVELOPS"
    INVESTS_IN = "INVESTS_IN"
    USES = "USES"
    COMPETES_WITH = "COMPETES_WITH"
    SUPPLIES_TO = "SUPPLIES_TO"
    REGULATED_BY = "REGULATED_BY"
    MENTIONED_IN = "MENTIONED_IN"
    PART_OF = "PART_OF"
    LEADS = "LEADS"
    ACQUIRES = "ACQUIRES"
    ENABLES = "ENABLES"
    DISRUPTS = "DISRUPTS"
    # --- Strategic / Causal ---
    DEPENDS_ON = "DEPENDS_ON"       # upstream dependency (supply chain)
    CONSTRAINS = "CONSTRAINS"       # bottleneck / regulatory constraint
    SUPPLIES = "SUPPLIES"           # direct material/component supplier
    BENEFITS_FROM = "BENEFITS_FROM" # second-order thematic beneficiary
    REPLACES = "REPLACES"           # displacement / substitution
    ENABLED_BY = "ENABLED_BY"       # requires an upstream enabler
    EXPOSED_TO = "EXPOSED_TO"       # risk exposure (geopolitical, regulatory)


class SignalDirection(str, Enum):
    POSITIVE = "positive"
    NEGATIVE = "negative"
    NEUTRAL = "neutral"


class ThemeConviction(str, Enum):
    EMERGING = "emerging"
    DEVELOPING = "developing"
    CONFIRMED = "confirmed"
    DECLINING = "declining"


@dataclass
class OntologyNode:
    """A node in the knowledge graph."""
    name: str
    node_type: NodeType
    properties: dict = field(default_factory=dict)
    mention_count: int = 1
    first_seen_at: Optional[date] = None
    last_seen_at: Optional[date] = None
    importance_score: float = 0.0
    neo4j_id: Optional[str] = None

    def __post_init__(self):
        if self.first_seen_at is None:
            self.first_seen_at = date.today()
        if self.last_seen_at is None:
            self.last_seen_at = date.today()

    @property
    def key(self) -> tuple:
        return (self.name.lower().strip(), self.node_type)


@dataclass
class OntologyEdge:
    """A directed relationship in the knowledge graph."""
    source_name: str
    source_type: NodeType
    relation: RelationType
    target_name: str
    target_type: NodeType
    weight: float = 1.0
    properties: dict = field(default_factory=dict)
    first_seen_at: Optional[date] = None
    last_seen_at: Optional[date] = None
    neo4j_rel_id: Optional[str] = None

    def __post_init__(self):
        if self.first_seen_at is None:
            self.first_seen_at = date.today()
        if self.last_seen_at is None:
            self.last_seen_at = date.today()

    @property
    def key(self) -> tuple:
        return (self.source_name.lower(), self.relation, self.target_name.lower())


@dataclass
class GraphEvent:
    """An ontology change event (for temporal tracking)."""
    event_type: str             # node_added | edge_added | weight_increased | node_removed
    entity_name: str
    entity_type: NodeType
    relation: Optional[RelationType] = None
    target_name: Optional[str] = None
    delta: float = 0.0
    event_date: Optional[date] = None
    document_id: Optional[int] = None
    metadata: dict = field(default_factory=dict)

    def __post_init__(self):
        if self.event_date is None:
            self.event_date = date.today()


@dataclass
class InvestmentTheme:
    """A detected cross-sector investment theme.

    Canonicalization fields (set by ThemeCanonicalizer after detection):
        is_canonical:       True  → this is a top-level parent theme shown in the UI.
                            False → this is a subtheme; rolled up under parent_theme_slug.
        canonical_name:     Clean human-readable name generated by the merge engine
                            (e.g. "AI Infrastructure Power Constraint").
        aliases:            Alternative names for the same macro-theme (canonical only).
        parent_theme_slug:  slug of the canonical parent; None when is_canonical=True.
    """
    theme_name: str
    theme_slug: str
    description: str = ""
    sectors: list[str] = field(default_factory=list)
    signal_types: list[str] = field(default_factory=list)
    strength_score: float = 0.0
    momentum_score: float = 0.0
    conviction: ThemeConviction = ThemeConviction.EMERGING
    first_detected: Optional[date] = None
    last_updated: Optional[date] = None
    doc_count: int = 0
    company_count: int = 0
    hypothesis_text: str = ""
    metadata: dict = field(default_factory=dict)
    # ── Canonicalization fields ───────────────────────────────────────────────
    is_canonical: bool = True
    canonical_name: str = ""
    aliases: list[str] = field(default_factory=list)
    parent_theme_slug: Optional[str] = None
    country: str = "US"

    def __post_init__(self):
        # NOTE: first_detected intentionally left as None when not yet confirmed.
        # Defaulting to date.today() caused future leakage in replay mode and
        # mass-clustering of themes to the same wall-clock date.
        # It will be set only after multi-quarter evidence crosses threshold.
        if self.last_updated is None:
            self.last_updated = date.today()
        if not self.theme_slug:
            self.theme_slug = self.theme_name.lower().replace(" ", "-").replace("/", "-")
        if not self.canonical_name:
            self.canonical_name = self.theme_name

    def to_dict(self) -> dict:
        return {
            "theme_name":        self.theme_name,
            "theme_slug":        self.theme_slug,
            "description":       self.description,
            "sectors":           self.sectors,
            "signal_types":      self.signal_types,
            "strength_score":    self.strength_score,
            "momentum_score":    self.momentum_score,
            "conviction":        self.conviction.value,
            "first_detected":    str(self.first_detected) if self.first_detected else None,
            "last_updated":      str(self.last_updated),
            "doc_count":         self.doc_count,
            "company_count":     self.company_count,
            "hypothesis_text":   self.hypothesis_text,
            "metadata":          self.metadata,
            # Canonicalization
            "is_canonical":      self.is_canonical,
            "canonical_name":    self.canonical_name,
            "aliases":           self.aliases,
            "parent_theme_slug": self.parent_theme_slug,
            "country":           self.country,
        }


@dataclass
class ThemeBeneficiary:
    """A company or entity that benefits from an investment theme."""
    theme_slug: str
    entity_name: str
    ticker: Optional[str] = None
    company_name: str = ""
    beneficiary_type: str = "direct"     # direct | indirect | disruptee
    company_role: str = ""               # infrastructure_provider | supplier | bottleneck_player | beneficiary | downstream_user | hidden_enabler
    relevance_score: float = 0.0
    signal_count: int = 0
    first_seen_at: Optional[date] = None
    last_seen_at: Optional[date] = None
    rank_in_theme: Optional[int] = None
    reasoning: str = ""

    def __post_init__(self):
        if not self.company_name:
            self.company_name = self.entity_name
        if self.first_seen_at is None:
            self.first_seen_at = date.today()
        if self.last_seen_at is None:
            self.last_seen_at = date.today()


# -------------------------------------------------------
# EVENT-CENTRIC ARCHITECTURE
# -------------------------------------------------------

class EventType(str, Enum):
    FACTORY_EXPANSION = "factory_expansion"
    FACTORY_CLOSURE = "factory_closure"
    SHORTAGE = "shortage"
    OVERSUPPLY = "oversupply"
    PRICE_INCREASE = "price_increase"
    PRICE_DECREASE = "price_decrease"
    EXPORT_RESTRICTION = "export_restriction"
    IMPORT_RESTRICTION = "import_restriction"
    INVESTMENT_ANNOUNCEMENT = "investment_announcement"
    PARTNERSHIP_ANNOUNCEMENT = "partnership_announcement"
    ACQUISITION = "acquisition"
    REGULATORY_APPROVAL = "regulatory_approval"
    REGULATORY_BAN = "regulatory_ban"
    TECHNOLOGY_BREAKTHROUGH = "technology_breakthrough"
    DEMAND_SURGE = "demand_surge"
    DEMAND_COLLAPSE = "demand_collapse"
    SUPPLY_CHAIN_DISRUPTION = "supply_chain_disruption"
    HIRING_ANNOUNCEMENT = "hiring_announcement"


@dataclass
class BusinessEvent:
    """A discrete business event extracted from a filing or transcript.

    Events are the atomic unit of the event-centric architecture.
    Markets react to events, not raw document text.
    """
    event_type: EventType
    subject_entity: str             # company / technology / commodity being affected
    subject_type: NodeType = NodeType.COMPANY
    description: str = ""
    magnitude: Optional[float] = None      # quantified size if present
    magnitude_unit: str = ""               # USD_bn, pct, units
    direction: str = "positive"            # positive | negative | neutral
    confidence: float = 0.75
    document_id: Optional[int] = None
    filed_at: Optional[date] = None
    context_text: str = ""
    second_order_entities: list[str] = field(default_factory=list)  # who else is affected
    metadata: dict = field(default_factory=dict)

    def __post_init__(self):
        if self.filed_at is None:
            self.filed_at = date.today()


# -------------------------------------------------------
# CAUSAL ONTOLOGY LAYER
# -------------------------------------------------------

@dataclass
class CausalLink:
    """A single step in a causal chain."""
    cause: str              # entity / concept name
    cause_type: NodeType
    effect: str             # entity / concept name
    effect_type: NodeType
    mechanism: str = ""     # short description of how cause → effect
    probability: float = 0.7
    lag_days: int = 90      # typical lag between cause and effect manifesting
    relation: RelationType = RelationType.ENABLES


@dataclass
class CausalChain:
    """A multi-hop causal chain between themes and entities.

    Example:
        AI Datacenter Buildout
          → ENABLES → Power Demand Surge (lag 90d)
          → ENABLES → Transformer Shortage (lag 180d)
          → ENABLES → Copper Demand Increase (lag 270d)
    """
    chain_id: str
    name: str
    description: str = ""
    links: list[CausalLink] = field(default_factory=list)
    activation_score: float = 0.0   # how strongly this chain is firing right now
    first_detected: Optional[date] = None

    def __post_init__(self):
        if self.first_detected is None:
            self.first_detected = date.today()

    @property
    def depth(self) -> int:
        return len(self.links)

    @property
    def terminal_effect(self) -> Optional[str]:
        return self.links[-1].effect if self.links else None

    def activation_summary(self) -> dict:
        return {
            "chain_id": self.chain_id,
            "name": self.name,
            "depth": self.depth,
            "terminal_effect": self.terminal_effect,
            "activation_score": self.activation_score,
        }


# -------------------------------------------------------
# NARRATIVE PROPAGATION
# -------------------------------------------------------

@dataclass
class NarrativePropagation:
    """Tracks how a narrative spreads across companies and sectors over time.

    A narrative is confirmed when the same theme is independently mentioned
    by companies across different sectors within a rolling time window.
    """
    narrative_slug: str
    narrative_name: str
    origin_company: str
    origin_date: Optional[date] = None
    propagation_trail: list[dict] = field(default_factory=list)
    # Each entry: {"company": str, "sector": str, "date": str, "signal_type": str}
    sector_spread: list[str] = field(default_factory=list)
    velocity: float = 0.0           # mentions per 30-day window
    acceleration: float = 0.0       # change in velocity vs prior window
    diffusion_score: float = 0.0    # 0-100 breadth of spread
    is_confirmed: bool = False

    def __post_init__(self):
        if self.origin_date is None:
            self.origin_date = date.today()

    def add_propagation(self, company: str, sector: str, event_date: date, signal_type: str):
        self.propagation_trail.append({
            "company": company,
            "sector": sector,
            "date": str(event_date),
            "signal_type": signal_type,
        })
        if sector not in self.sector_spread:
            self.sector_spread.append(sector)
        if len(self.sector_spread) >= 3:
            self.is_confirmed = True
